server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}}/eureka/
    register-with-eureka: false
spring:
  application:
    name: eureka